name: aws-v5
on:
  push:
    branches:
      - main

# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build: # 마음대로 적어도됨.
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout # not need 1.action code download lib
        uses: actions/checkout@v2 #google see ok easy code download
      - name: Set up JDK # not need 2.action jdk download lib
        uses: actions/setup-java@v1 #google see ok easy code download
        with:
          java-version: 11
      - name: Grant execute permission for gradlew # not need 3.script
        run: chmod +x ./gradlew # 실행권한을 bash로 줍니다.
        shell: bash 
      - name: Build with Gradle # not need 4.script
        run: ./gradlew clean build #빌드를 bash로 줍니다.
        shell: bash